/* tslint:disable */
// generated by typescript-json-validator
import Ajv from 'ajv';
import {
  LoginInput,
  ChangePasswordInput,
  SignupInput,
} from './auth.controller.types';
export const ajv = new Ajv({
  allErrors: true,
  coerceTypes: false,
  format: 'fast',
  nullable: true,
  unicode: true,
  uniqueItems: true,
  useDefaults: true,
});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

export { LoginInput, ChangePasswordInput, SignupInput };
export const Schema = {
  $id: './src/controllers/auth/auth.controller.types.ts',
  $schema: 'http://json-schema.org/draft-07/schema#',
  definitions: {
    ChangePasswordInput: {
      additionalProperties: false,
      defaultProperties: [],
      properties: {
        currentPassword: {
          type: 'string',
        },
        email: {
          type: 'string',
        },
        newPassword: {
          type: 'string',
        },
        rePassword: {
          type: 'string',
        },
      },
      required: ['currentPassword', 'email', 'newPassword', 'rePassword'],
      type: 'object',
    },
    LoginInput: {
      additionalProperties: false,
      defaultProperties: [],
      properties: {
        email: {
          type: 'string',
        },
        password: {
          type: 'string',
        },
      },
      required: ['email', 'password'],
      type: 'object',
    },
    SignupInput: {
      additionalProperties: false,
      defaultProperties: [],
      properties: {
        email: {
          type: 'string',
        },
        name: {
          type: 'string',
        },
        password: {
          type: 'string',
        },
        rePassword: {
          type: 'string',
        },
      },
      required: ['email', 'name', 'password', 'rePassword'],
      type: 'object',
    },
  },
};
ajv.addSchema(Schema, 'Schema');
export function validate(
  typeName: 'LoginInput',
): (value: unknown) => LoginInput;
export function validate(
  typeName: 'ChangePasswordInput',
): (value: unknown) => ChangePasswordInput;
export function validate(
  typeName: 'SignupInput',
): (value: unknown) => SignupInput;
export function validate(typeName: string): (value: unknown) => any {
  const validator: any = ajv.getSchema(`Schema#/definitions/${typeName}`);
  return (value: unknown): any => {
    if (!validator) {
      throw new Error(
        `No validator defined for Schema#/definitions/${typeName}`,
      );
    }

    const valid = validator(value);

    if (!valid) {
      throw new Error(
        'Invalid ' +
          typeName +
          ': ' +
          ajv.errorsText(
            validator.errors!.filter((e: any) => e.keyword !== 'if'),
            { dataVar: typeName },
          ),
      );
    }

    return value as any;
  };
}
