version: '3'

services:
  postgres:
    env_file:
      - .docker.dev.env
    ports:
      - 5454:5432

  itask:
    build:
      context: .
      dockerfile: itask.dev.Dockerfile
    ports:
      # - HOST:CONTAINER
      - 4000:4000
    env_file:
      - .docker.dev.env
    volumes:
      - ./:/app
      - /app/dist
      - /app/node_modules

  # add pgadmin4 to manage PostreSQL database
  pgadmin4:
    container_name: itask-pgadmin4
    image: dpage/pgadmin4
    env_file:
      - .docker.dev.env
    ports:
      - 8080:80