version: '3'

services:
  postgres:
    env_file:
      - .docker.prod.env

  itask:
    build:
      context: .
      dockerfile: itask.Dockerfile
    ports:
      # - HOST:CONTAINER
      - 4000:4000
    env_file:
      - .docker.prod.env
    depends_on:
      - postgres
