version: '3'

services:
  postgres:
    container_name: itask-postgres
    build:
      context: .
      dockerfile: db.Dockerfile
    volumes:
      - postgres-data:/var/lib/postgresql/data

  itask:
    container_name: itask-server
    depends_on:
      - postgres

volumes:
  postgres-data: