#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    \set POSTGRES_ITASK_DB `echo $POSTGRES_ITASK_DB`
    \set POSTGRES_ITASK_USER `echo $POSTGRES_ITASK_USER`
    \set POSTGRES_ITASK_PASSWORD `echo $POSTGRES_ITASK_PASSWORD`
    CREATE ROLE :POSTGRES_ITASK_USER 
    LOGIN 
    PASSWORD :POSTGRES_ITASK_PASSWORD;
    CREATE DATABASE :POSTGRES_ITASK_DB;
EOSQL