#!/bin/bash

if [ -z "$1" ] 
then
  echo "❌ Required to provide Heroku APP_NAME 😬"
  exit 0
fi

APP_NAME=$1

deploy() {
  echo "Deploying your app $APP_NAME to Heroku...📡"
  echo "> Step 1: Building Docker image..."
  heroku container:push web -a $APP_NAME
  echo "> Step 1: Done ✅"

  echo "> Step 2: Releasing.."
  heroku container:release web -a $APP_NAME
  echo "> Step 2: Done ✅"

  echo "> Step 3: Deploying Prisma schema..."
  heroku run npm run prisma:deploy -a $APP_NAME
  echo "> Step 3: Done ✅"
  echo "Deployed '$APP_NAME' success 🤩🎇✨🎉"
}

WHO_AM_I=$(heroku whoami 2> /dev/null)

if [[ -z $WHO_AM_I ]]; then
  echo "⛔ You're logged in. Please login"

  # Login heroku 
  heroku login

  # Login heroku registry
  heroku container:login
fi

deploy