type Todo {
  id: Int!
  userId: Int!
  title: String!
  completed: Boolean!
}

input SearchTodoParams {
  id: Int
  title: String
  completed: Boolean
}

extend type Query {
  searchTodos(userId: Int!, searchParams: SearchTodoParams): [Todo!]!
}
