# type Query {
#   helloWorld: String!
# }

# type Mutation {
#   hello(msg: String!): Bool!
# }

type Query {
  _empty: String
}

type Mutation {
  _empty: String
}

schema {
  query: Query
  mutation: Mutation
}
